[workspace]
name = "loch"
channels = ["conda-forge", "openbiosim/label/dev"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.10"
biosimspace = "*"
loguru = "*"
pyopencl = "*"

[target.linux-64.dependencies]
pycuda = "*"
ocl-icd = "*"
ocl-icd-system = "*"

[target.osx-arm64.dependencies]
khronos-opencl-icd-loader = "*"
ocl_cd_wrapper_apple = "*"

[target.windows-64.dependencies]
pycuda = "*"
khronos-opencl-icd-loader = "*"

[feature.test.dependencies]
pytest = "*"
black = "*"

[feature.lint.dependencies]
pre-commit = "*"
rattler-build = "*"
ruff = "*"

[environments]
default = []
test = ["test"]
dev = ["test", "lint"]
